"""
Django settings for wechat_auto_reply project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# tecent wework configurations
WEWORK_TOKEN = 'abcdef' # change to your own token
WEWORK_AES_KEY = '123456' # change to your own aes key
WEWORK_CORP_ID = 'abcxyz' # change to your own corp id
WEWORK_CORP_SECRET = '123890' # change to your own corp secret
WEWORK_AGENT_ID = 1000000

# gpt configurations
OPENAI_API_KEY = '123456' # fill in your openai api key
OPENAI_GPT_ENGINE = 'gpt-4' # gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0310
OPENAI_SYSTEM_PROMPT = '你是江南皮革厂自研的JNGPT，基于国产自研大模型实现，接下来用中文进行对话，适量使用emoji，并用尽可能简短的文字来回答。' # change to your own system prompt
OPENAI_SEARCH_PROMPT = '你需要结合一些网络上检索到的信息和你已经掌握的知识库，对一个问题给出尽可能简洁、思考再三后的解答。'

# chat configurations
CHAT_RESET_MESSAGE = '重置对话' # change to your own reset message
CHAT_RESET_MESSAGE_RESULT = '重置对话成功！' # change to your own reset message result
CHAT_ERROR_MESSAGE = 'GPT API 压力大，请稍后再试' # change to your own error message
CHAT_GOOGLE_ERROR_MESSAGE = '联网计算失败，请稍后重试！' # change to your own error message after google search

# google api configurations
# 可以参考 https://significant-gravitas.github.io/Auto-GPT/configuration/search/
GOOGLE_API_KEY = 'zbxlkjselgjkxb0s9dgljejk23'
CUSTOM_SEARCH_ENGINE_ID = '8b23bsdo'
SEARCH_OPTIONS_COUNT = 3
SEARCH_TOKEN = ['搜一下', '搜一搜', '联网', '连网']

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oiizqyaszf8ha+t#=8720&3tw7&=6r=txlfe)=$p)gfkv6+w-w'
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
REDIS_HOST = 'redis'
REDIS_PORT = 6379

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'message_handler',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wechat_auto_reply.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wechat_auto_reply.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
